### ISSUE TITLE
Select option attribute is not possible to set

### ISSUE THREAD

**Issue by escopecz** [joomla-framework/form#17]
When building an option tag, there is code to set an attribute:

```
if (isset($element[$options['option.attr']]))
{
    $attr = $element[$options['option.attr']];
}
```

https://github.com/joomla-framework/form/blob/master/src/Html/Select.php#L580

But that requires to set $options['option.attr'] which is null by default and is not possible to set to different value outside of the Select class. Or I can't see how to change it. Somebody can?

**Comment by escopecz** [comment]
Do you think it could be changed to this?:
```
if (isset($element['attr]))
{
    $attr = $element['attr'];
}
```

**Comment by mbabker** [comment]
You can try it and see what happens.  I'd be interested to know if it works in the CMS but not here (the method is the same as in `JHtmlSelect::options()` in that repo).

**Comment by escopecz** [comment]
Tried and works. Here is my use case: I have this custom field:
```
<?php
namespace App\Form\Field;

use Joomla\Form\Html\Select as HtmlSelect;

class PlansField extends \Joomla\Form\Field\ListField
{
    /**
     * The form field type.
     *
     * @var    string
     * @since  1.0
     */
    protected $type = 'Plans';
    
    public function getInput()
    {
        return parent::getInput();
    }

    /**
     * Method to get the field options.
     *
     * @return  array  The field option objects.
     *
     * @since   1.0
     */
    protected function getOptions()
    {
        $options = parent::getOptions();
        $app = $this->form->getApp();
        $planModel = $app->getModel('plan');
        $plans = $planModel->loadItems();
        
        $select = new HtmlSelect;

        foreach ($plans as $plan)
        {
            $attrs = array('option.attr' => 'attr', 'attr' => array('data-price' => $plan->price));
            $options[] = $select->option($plan->id, $plan->name . ' ($' . $plan->price . ')', $attrs, 'text');
        }

        reset($options);

        return $options;
    }
}
```
Option object I create looks like this:
```
object(stdClass)#792 (4) {
    ["value"]=>
    string(1) "1"
    ["text"]=>
    string(15) "StartUp ($4.95)"
    ["attr"]=>
    array(1) {
      ["data-price"]=>
      string(4) "4.95"
    }
    ["disable"]=>
    bool(false)
}
```
If I modify Select class as I suggested, option attribute will appear:
```
<option value="1" data-price="4.95">StartUp ($4.95)</option>
```

Or, if we wouldn't want to change existing code, we can add a method to Select class:
```
public functions setDefaultOptions(array $options)
{
    $this->optionDefaults = array_merge(
	$this->optionDefaults,
        $options
    );
}
```
This way I could do at getOptions() method this:
```
$select = new HtmlSelect;
$select->setDefaultOptions(array('option.attr' => 'attr'));
```
What do you think?

**Comment by mbabker** [comment]
If your original suggestion fixes the issue then I'd suggest making a pull for that.  I'd also suggest testing it in the CMS and sending a pull there with the same fix as the class there is coded the same way.  If it works in the CMS as it is but not here, I'd be interested to know what we broke.

**Comment by wilsonge** [comment]
Probably rather than us breaking it means the cms fixed it :P

**Comment by escopecz** [comment]
PR: https://github.com/joomla-framework/form/pull/18

**Comment by mbabker** [comment]
Package is deprecated (and for me at least abandoned).
