### ISSUE TITLE
Allow passing arguments to form entities (Fields, Rules)

### ISSUE THREAD

**Issue by piotr-cz** [joomla-framework/form#2]
One thing I'm missing since we've removed Factory from framework is passing data to Form entities (Fields and Rules), like a DIC.

Scenaraio:
one Rule I've build has an option to check for uniqueness of the value, for that I need an access to database and that's what I'd like to retrieve from container.

**Comment by mbabker** [comment]
Package is deprecated (and for me at least abandoned).
