### ISSUE TITLE
Repeatable form field type breaks when used with User form field type

### ISSUE THREAD

**Issue by photodude** [joomla-framework/form#25]
The [Repeatable form field type](https://docs.joomla.org/Repeatable_form_field_type) breaks when used with [User form field type](https://docs.joomla.org/User_form_field_type)

**Replication steps**
1. Create a standard XML form and view for a component
2. Use the Repeatable form field type to call the User form field type as the repeatable field

Example XML code
```
<field name="list_users"
	type="Repeatable"
	icon="list"
	description="PLG_TINY_FIELD_TEMPLATE_FIELD_ELEMENTS_DESC"
	label="PLG_TINY_FIELD_TEMPLATE_FIELD_ELEMENTS_LABEL"
	default="{'user':['']}">
	<fields name="params">
	<fieldset hidden="true" name="list_users_modal" repeat="true">
		<field name="user_id" type="user"
			label="JGLOBAL_FIELD_MODIFIED_BY_LABEL"
			filter="unset" />
	</fieldset>
	</fields>
</field>
```
**Expected:** a repeatable field for users that would display a modal field list of selected users, which upon "adding" a user would display a modal select box of users. 
**Result observed:** the modal select box of users does not display as a modal but replaces the existing view with a user list and no method to return to the component view after selecting a user.

**Comment by mbabker** [comment]
Can you file this issue on the CMS repo?  The Framework doesn't have either of those form fields within it.

**Comment by photodude** [comment]
@mbabker Thanks for the heads up I'll move it, I had mistakenly assumed this was an issue in the Framework since these fields are located in the library of the CMS repo. (sometimes it's hard to tell what's in the framework vs what's specific to the CMS when looking at the CMS)

**Comment by mbabker** [comment]
Easiest way to distinguish it right now is code in the libraries/vendor folder is a repo external to the CMS (including Framework packages) and most everything else is the CMS code (either native to it or still needing converted to using its Framework counterpart).

**Comment by photodude** [comment]
@mbabker Thanks for the tip.
