### ISSUE TITLE
Invalid documentation - Creating Custom Fields

### ISSUE THREAD

**Issue by Twister1002** [joomla-framework/form#36]
I highly recommend you update your documentation. I spent the last 2 hours researching an issue that your documentation said was correct.

Please use this for your documentation

    namespace Joomla\Form;

    class Field_<type> extends \Joomla\Form\Field
    {
	
      public $type = '<type>';
	
      // Override this function
      protected function getInput()
      {
	      $class = !empty($this->class) ? $this->class : "";
	      return "<input class='$class' type='button' value='Agree' id='$this->id;' name='$this->name;'>";
      }
    }

**Comment by mbabker** [comment]
Which documentation?  For the 1.x branch that is the correct example but not the same for the 2.0 master branch.

**Comment by mbabker** [comment]
Nevermind.  Saw the 1.x README was bad, fixed it.

**Comment by Twister1002** [comment]
I Apologize, this is for the 1.2 Dev. 

However the changes you made will still reflect an error when implementing. Notice the change in the Namespace that I provided. 

    namespace Joomla\Form;

The namespace scheme you provide will just throw an error.

**Comment by mbabker** [comment]
Should be fixed now.  I don't know if the sub-namespace example will actually work with this structure or not though.
