### ISSUE TITLE
Different implementation of int & int_array filters.

### ISSUE THREAD

**Issue by Achal-Aggarwal** [joomla-framework/form#4]
In Form::filterField method there is filter for 'int_array' which is using ArrayHelper::toInteger and to filter 'int' it is delegating to InputFilter::clean method.  so if 'A1B2C3' is filtered as int then 1 is returned, but if array('A1B2C3') is filtered as int_array then array(0) is returned.

I guess this is because of different implementation of typecasting to int in "ArrayHelper::toInteger" & in "InputFilter::clean".

If we use explicit typecasting then (int) "A1B2C3" => 0, (int) "1A2B3C" => 1 . Am I correct?

**Comment by mbabker** [comment]
Package is deprecated (and for me at least abandoned).
